name: Scala

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Scala CI
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.14
      - name: Test
        run: sbt coverage test coverageAggregate
      - name: Format and Lint
        run: sbt scalafmtCheckAll scalafmtSbtCheck 'scalafixAll --check'
      - uses: codecov/codecov-action@v1
